[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#111117"
textColor = "#F4F4F5"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 50
